### ISSUE TITLE
Create a verify token middleware

### ISSUE THREAD

**Issue by ronanfitz** [Place-Me/Place-Me#8]
New module.

Transform into middleware!
`function verifyToken(token) {
  if (token) {
    jwt.verify(token, process.env.JWT_TOKEN, (err, decoded) => {
      if (err) {
        console.log("VERIFICATION ERROR:", err);
        return res.sendStatus(401);
      }
      return decoded;
    });
  }
}`

**Comment by ronanfitz** [comment]
const verifyToken = require("...");

verify = middleware
router.post('/login', verifyToken, (req, res) ... });

**Comment by tylerlan** [comment]
```
function verifyToken(req, res, next) {
  let token = req.cookies.token;
  if (token) {
    jwt.verify(token, process.env.JWT_KEY, (err, decoded) => {
      if (err) {
        return res.sendStatus(401);
      }
      next();
    });
  } else {
    return res.sendStatus(404);
  }
}
```
